CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    employee_number VARCHAR(50) NOT NULL,
    name_en VARCHAR(200) NOT NULL,
    name_ar VARCHAR(200),
    designation_en VARCHAR(200),
    designation_ar VARCHAR(200),
    date_of_joining DATE,
    passport_number VARCHAR(100),
    civil_id VARCHAR(100),
    basic_salary NUMERIC(14, 3) NOT NULL DEFAULT 0,
    bank_name VARCHAR(200),
    bank_account_number VARCHAR(100),
    iban VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_employees_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_employees_tenant_employee_number
        UNIQUE (tenant_id, employee_number),

    CONSTRAINT uq_employees_tenant_id_id
        UNIQUE (tenant_id, id),

    CONSTRAINT ck_employees_basic_salary
        CHECK (basic_salary >= 0),

    CONSTRAINT ck_employees_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX uq_employees_tenant_passport_number
    ON employees (tenant_id, passport_number)
    WHERE passport_number IS NOT NULL;

CREATE UNIQUE INDEX uq_employees_tenant_civil_id
    ON employees (tenant_id, civil_id)
    WHERE civil_id IS NOT NULL;

CREATE INDEX ix_employees_tenant_status
    ON employees (tenant_id, status);

CREATE TABLE employee_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    employee_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    check_in TIME,
    check_out TIME,
    remarks TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_employee_attendance_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_employee_attendance_tenant_employee
        FOREIGN KEY (tenant_id, employee_id)
        REFERENCES employees (tenant_id, id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_employee_attendance_tenant_employee_date
        UNIQUE (tenant_id, employee_id, attendance_date),

    CONSTRAINT ck_employee_attendance_status
        CHECK (
            status IN (
                'PRESENT',
                'ABSENT',
                'LEAVE',
                'SICK',
                'HOLIDAY'
            )
        )
);

CREATE INDEX ix_employee_attendance_tenant_date
    ON employee_attendance (tenant_id, attendance_date);

CREATE TABLE salary_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    employee_id BIGINT NOT NULL,
    salary_month SMALLINT NOT NULL,
    salary_year SMALLINT NOT NULL,
    basic_salary NUMERIC(14, 3) NOT NULL,
    allowances NUMERIC(14, 3) NOT NULL DEFAULT 0,
    deductions NUMERIC(14, 3) NOT NULL DEFAULT 0,
    net_salary NUMERIC(14, 3)
        GENERATED ALWAYS AS (
            basic_salary + allowances - deductions
        ) STORED,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    payment_date DATE,
    remarks TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_salary_payments_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_salary_payments_tenant_employee
        FOREIGN KEY (tenant_id, employee_id)
        REFERENCES employees (tenant_id, id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_salary_payments_tenant_employee_period
        UNIQUE (
            tenant_id,
            employee_id,
            salary_month,
            salary_year
        ),

    CONSTRAINT ck_salary_payments_month
        CHECK (salary_month BETWEEN 1 AND 12),

    CONSTRAINT ck_salary_payments_year
        CHECK (salary_year BETWEEN 2000 AND 2100),

    CONSTRAINT ck_salary_payments_amounts
        CHECK (
            basic_salary >= 0
            AND allowances >= 0
            AND deductions >= 0
            AND deductions <= basic_salary + allowances
        ),

    CONSTRAINT ck_salary_payments_status
        CHECK (payment_status IN ('PENDING', 'PAID')),

    CONSTRAINT ck_salary_payments_payment_date
        CHECK (
            payment_status <> 'PAID'
            OR payment_date IS NOT NULL
        )
);

CREATE INDEX ix_salary_payments_tenant_period
    ON salary_payments (tenant_id, salary_year, salary_month);

CREATE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_tenants_set_updated_at
BEFORE UPDATE ON tenants
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_employees_set_updated_at
BEFORE UPDATE ON employees
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_employee_attendance_set_updated_at
BEFORE UPDATE ON employee_attendance
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_salary_payments_set_updated_at
BEFORE UPDATE ON salary_payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();