CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    department_code VARCHAR(50) NOT NULL,
    name_en VARCHAR(200) NOT NULL,
    name_ar VARCHAR(200),
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_departments_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_departments_tenant_code
        UNIQUE (tenant_id, department_code),

    CONSTRAINT uq_departments_tenant_id_id
        UNIQUE (tenant_id, id),

    CONSTRAINT ck_departments_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_departments_tenant_status_name
    ON departments (tenant_id, status, name_en);

INSERT INTO departments (
    tenant_id,
    department_code,
    name_en,
    name_ar
)
SELECT
    id,
    'GENERAL',
    'General',
    'عام'
FROM tenants
ON CONFLICT (tenant_id, department_code) DO NOTHING;

ALTER TABLE employees
    ADD COLUMN department_id BIGINT,
    ADD COLUMN work_email VARCHAR(320),
    ADD COLUMN personal_email VARCHAR(320),
    ADD COLUMN phone_number VARCHAR(50),
    ADD COLUMN alternate_phone_number VARCHAR(50),
    ADD COLUMN date_of_birth DATE,
    ADD COLUMN gender VARCHAR(20),
    ADD COLUMN nationality VARCHAR(100),
    ADD COLUMN employment_type VARCHAR(30) NOT NULL DEFAULT 'FULL_TIME',
    ADD COLUMN present_address TEXT,
    ADD COLUMN permanent_address TEXT,
    ADD COLUMN emergency_contact_name VARCHAR(200),
    ADD COLUMN emergency_contact_phone VARCHAR(50),
    ADD COLUMN emergency_contact_relationship VARCHAR(100),
    ADD COLUMN photo_storage_key VARCHAR(500),
    ADD COLUMN photo_file_name VARCHAR(255),
    ADD COLUMN photo_content_type VARCHAR(100),

    ADD CONSTRAINT fk_employees_tenant_department
        FOREIGN KEY (tenant_id, department_id)
        REFERENCES departments (tenant_id, id)
        ON DELETE RESTRICT,

    ADD CONSTRAINT ck_employees_gender
        CHECK (
            gender IS NULL
            OR gender IN ('MALE', 'FEMALE', 'OTHER')
        ),

    ADD CONSTRAINT ck_employees_employment_type
        CHECK (
            employment_type IN (
                'FULL_TIME',
                'PART_TIME',
                'CONTRACT',
                'TEMPORARY'
            )
        );

CREATE UNIQUE INDEX uq_employees_tenant_work_email
    ON employees (tenant_id, lower(work_email))
    WHERE work_email IS NOT NULL;

CREATE INDEX ix_employees_tenant_department
    ON employees (tenant_id, department_id);

CREATE INDEX ix_employees_search
    ON employees
    USING GIN (
        (
            employee_number || ' ' || name_en || ' ' ||
            COALESCE(name_ar, '') || ' ' ||
            COALESCE(civil_id, '') || ' ' ||
            COALESCE(work_email, '') || ' ' ||
            COALESCE(phone_number, '')
        ) gin_trgm_ops
    );

CREATE TABLE holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    holiday_name_en VARCHAR(200) NOT NULL,
    holiday_name_ar VARCHAR(200),
    holiday_date DATE NOT NULL,
    holiday_type VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    is_recurring BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_holidays_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES tenants (id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_holidays_tenant_date_name
        UNIQUE (tenant_id, holiday_date, holiday_name_en),

    CONSTRAINT ck_holidays_type
        CHECK (holiday_type IN ('PUBLIC', 'COMPANY')),

    CONSTRAINT ck_holidays_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_holidays_tenant_date
    ON holidays (tenant_id, holiday_date);

CREATE TRIGGER trg_departments_set_updated_at
BEFORE UPDATE ON departments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_holidays_set_updated_at
BEFORE UPDATE ON holidays
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
