services:
  database:
    image: postgres:16
    container_name: citenest-site-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - citenest_site_db_data:/var/lib/postgresql/data

volumes:
  citenest_site_db_data:
